version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./sql/initialize/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/operadores_csv:/var/lib/mysql-files/operadores_csv
      - ./data/demonstrativos_csv:/var/lib/mysql-files/demonstrativos_csv

    command: --secure-file-priv=""
